H\PlatformBundle\Entity\Image:
    type: entity
    table: null
    repositoryClass: H\PlatformBundle\Repository\ImageRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 255
            unique: true
        path:
            type: string
            length: 255
            unique: true
    lifecycleCallbacks: {  }
